Repository fga-gpp-mds/2018.1_Gerencia_mais, pull requests merged in 2018-05, with the labels that each got.

#148 Is144 sprint 6
  docs/documentos/Sprints/Sprint_6_Planejamento.md
  docs/documentos/Sprints/Sprint_6_Resultados.md
  docs/documentos/imagens/Sprint6/burndown_s6.png
  docs/documentos/imagens/Sprint6/pareamento_s6.png
  docs/documentos/imagens/Sprint6/quadro_conhecimento.png
  docs/documentos/imagens/Sprint6/retrospectiva_s6.png
  docs/documentos/imagens/Sprint6/velocity_s6.png
Labels: [Documentation], [EPS], [Important], [Organization], [Sprint], [Technical Stories], [Urgent]

#154 Is147 sprint 7 Pull request
  docs/documentos/Sprints/Sprint_7_Planejamento.md
  docs/documentos/Sprints/Sprint_7_Resultados.md
  docs/documentos/imagens/Sprint7/burndown_s7.png
  docs/documentos/imagens/Sprint7/conhecimento_s7.png
  docs/documentos/imagens/Sprint7/pareamento_s6.png
  docs/documentos/imagens/Sprint7/retrospectiva_s7.png
  docs/documentos/imagens/Sprint7/velocity_s6.png
  docs/documentos/imagens/Sprint7/velocity_s7.png
Labels: [Documentation], [EPS], [Organization]

#167 Is163 sprint9 planning
  docs/documentos/Sprints/Sprint_8_Planejamento.md
  docs/documentos/Sprints/Sprint_8_Resultado.md
  docs/documentos/Sprints/Sprint_9_Planejamento.md
  docs/documentos/imagens/Sprint_9/pareamentos9.png
Labels: [Documentation], [EPS], [Important], [Organization], [Sprint], [Technical Stories]

#169 Is162 refatorar erros de apresentação
  docs/documentos/Mds/Documento_de_Arquitetura.md
  docs/documentos/Mds/Documento_de_Visao.md
  docs/pages/sprint.html
Labels: [Documentation], [EPS], [Important]

#170 Implementing Fetch on the popup
  src/pages/ScheduleTable.jsx
Labels: [Backend], [Frontend], [MDS], [React], [Technical Stories]

#176 Update key deploy
  .travis.yml
Labels: [Configuration], [DevOps], [EPS], [Heroku], [Homologação], [Produção], [Travis], [Urgent]

#183 Is136 criar permissoes login
  docker-compose.yml
  leito_hospitalar/settings.py
  leito_hospitalar/urls.py
  package-lock.json
  package.json
  schedule/views.py
  src/App.js
  src/actions/actions.js
  src/components/Footer.js
  src/components/NavBar.jsx
  src/components/NavBarLogged.jsx
  src/components/PrivateRouter.js
  src/components/SideBar.jsx
  src/components/store.js
  src/css/HomePage.css
  src/css/NavBar.css
  src/images/black_wallpaper.jpg
  src/index.js
  src/pages/DoctorForm.jsx
  src/pages/HomePage.jsx
  src/pages/LoginPage.jsx
  src/pages/RegistrationAdmin.jsx
  src/pages/ScheduleTable.jsx
  src/reducers/reducers.js
  user/__init__.py
  user/admin.py
  user/apps.py
  user/migrations/0001_initial.py
  user/migrations/0002_auto_20180507_2058.py
  user/migrations/__init__.py
  user/models.py
  user/serializers.py
  user/signals.py
  user/tests.py
  user/urls.py
  user/views.py
Labels: [Backend], [Django], [Frontend], [MDS], [React]

#185 Is184 retrospectiva sprint 9
  _site/documentos/Eps/Definicao-de-pronto.md
  _site/documentos/Eps/EVM.md
  _site/documentos/Sprints/Sprint_3_Resultados.md
  _site/documentos/Sprints/Sprint_4_Planejamento.md
  _site/documentos/Sprints/Sprint_4_Resultados.md
  _site/documentos/Sprints/Sprint_5_Planejamento.md
  _site/documentos/Sprints/Sprint_5_Resultados.md
  _site/documentos/imagens/Sprint3/burndown.png
  _site/documentos/imagens/Sprint3/retrospectiva.png
  _site/documentos/imagens/Sprint4/Pareamento.png
  _site/documentos/imagens/Sprint4/burndown.png
  _site/documentos/imagens/Sprint4/retrospectiva.png
  _site/documentos/imagens/Sprint5/Pareamento.png
  _site/documentos/imagens/Sprint5/burndown.png
  _site/documentos/imagens/Sprint5/quadro_de_conhecimento_r1.png
  _site/documentos/imagens/Sprint5/retrospectiva.png
  _site/documentos/imagens/horas_trabalhadas/grafico_eps.png
  _site/documentos/imagens/horas_trabalhadas/grafico_mds.png
  _site/documentos/imagens/horas_trabalhadas/horas_eps.png
  _site/documentos/imagens/horas_trabalhadas/horas_mds.png
  _site/documentos/imagens/sprint0/burndown.png
  _site/documentos/imagens/sprint1/burndown.png
  _site/documentos/imagens/sprint1/retrospectiva.png
  _site/documentos/imagens/sprint2/burndown.png
  _site/projectabout/index.html
  docs/documentos/Sprints/Sprint_9_Resultado.md
  docs/documentos/imagens/Sprint9/New Bitmap Image.bmp
  docs/documentos/imagens/Sprint9/burndown_s9.png
  docs/documentos/imagens/Sprint9/pareamentos9.png
  docs/documentos/imagens/Sprint9/retrospectiva_s9.png
  docs/documentos/imagens/Sprint9/velocity_s9.png
  docs/pages/sprint.html
  documentos/Eps/Definicao-de-pronto.md
  documentos/Eps/EVM.md
  documentos/Sprints/Sprint_3_Resultados.md
  documentos/Sprints/Sprint_4_Planejamento.md
  documentos/Sprints/Sprint_4_Resultados.md
  documentos/Sprints/Sprint_5_Planejamento.md
  documentos/Sprints/Sprint_5_Resultados.md
  documentos/imagens/Sprint3/burndown.png
  documentos/imagens/Sprint3/retrospectiva.png
  documentos/imagens/Sprint4/Pareamento.png
  documentos/imagens/Sprint4/burndown.png
  documentos/imagens/Sprint4/retrospectiva.png
  documentos/imagens/Sprint5/Pareamento.png
  documentos/imagens/Sprint5/burndown.png
  documentos/imagens/Sprint5/quadro_de_conhecimento_r1.png
  documentos/imagens/Sprint5/retrospectiva.png
  documentos/imagens/horas_trabalhadas/grafico_eps.png
  documentos/imagens/horas_trabalhadas/grafico_mds.png
  documentos/imagens/horas_trabalhadas/horas_eps.png
  documentos/imagens/horas_trabalhadas/horas_mds.png
  documentos/imagens/sprint0/burndown.png
  documentos/imagens/sprint1/burndown.png
  documentos/imagens/sprint1/retrospectiva.png
  documentos/imagens/sprint2/burndown.png
Labels: [Documentation], [EPS], [Important], [Organization], [Sprint], [Technical Stories]

#196 updating po roadmap
  docs/documentos/RoadMaps/roadmapPO.png
Labels: [EPS]

#227 Is225 planejamento da sprint 12
  docs/documentos/Sprints/Sprint_12_Planejamento.md
  docs/documentos/imagens/Sprint12/pareamento_s12.png
Labels: [Documentation], [EPS], [Important], [Organization], [Technical Stories], [Urgent]

#231 Is230 refatoraçao de codigo no frontend
  src/components/PrivateRouter.js
  src/components/store.js
  src/pages/DoctorForm.jsx
  src/pages/DoctorStatus.jsx
  src/pages/LoginPage.jsx
Labels: [Frontend], [MDS], [React]
