Repository fga-gpp-mds/2018.1_Gerencia_mais, pull requests merged in 2018-06, with the labels that each got.

#232 Private Router Bug Fix
  src/components/PrivateRouter.js
Labels: [Bug], [Frontend], [React]

#240 Is239 planejamento sprint 13
  docs/documentos/Sprints/Sprint_13_Planejamento
  docs/documentos/imagens/Sprint13/PAreamento Sprint 13.png
Labels: [Documentation], [EPS], [Important], [Technical Stories]

#244 Is234 alterar forma de atualizar evento medico
  doctor/tests.py
  doctor/views.py
  package-lock.json
  package.json
  schedule/views.py
  src/App.js
  src/components/Footer.js
  src/components/Form.jsx
  src/components/FormUpdate.jsx
  src/components/Modal.jsx
  src/components/NavBar.jsx
  src/components/SideBar.jsx
  src/css/DoctorForm.css
  src/css/HomePage.css
  src/css/Modal.css
  src/css/NavBar.css
  src/css/ScheduleTable.css
  src/css/SideBar.css
  src/css/bootstrap.css
  src/css/footer.css
  src/images/bookmark.png
  src/images/bookmark.svg
  src/images/doctor_schedule-512.png
  src/images/home-medicos.png
  src/index.css
  src/index.js
  src/pages/Dashboard.jsx
  src/pages/DoctorForm.jsx
  src/pages/DoctorStatus.jsx
  src/pages/HomePage.jsx
  src/pages/LoginPage.jsx
  src/pages/MyTable.jsx
  src/pages/NewScheduleTable.jsx
  src/pages/RegistrationAdmin.jsx
  src/pages/ScheduleTable.jsx
  src/pages/UpdateSchedule.jsx
  subtitle/tests.py
  subtitle/urls.py
  subtitle/views.py
Labels: [Backend], [Django], [Frontend], [MDS], [React], [User Stories]

#246 Is219 atualizar riscos
  docs/documentos/Eps/Detalhamento_de_Riscos.md
  docs/documentos/Eps/Gerenciamento_de_Riscos.md
  docs/documentos/Eps/registro_de_ocorrencia_de_riscos.md
Labels: [Documentation], [EPS], [Important], [Organization], [Sprint], [Urgent], [User Stories]

#256 arrumando bug no modal
  src/components/Modal.jsx
  src/css/bootstrap.css
Labels: [Bug], [Frontend], [MDS], [React]

#257 Is253 cadastrar medico pela tabela
  src/components/FormDoctorForm.jsx
  src/components/Modal.jsx
  src/components/ModalForm.jsx
  src/pages/ScheduleTable.jsx
Labels: [Frontend], [MDS], [React], [User Stories]

#259 Adding planing of sprint 14
  docs/documentos/Sprints/Sprint_13_Planejamento.md
  docs/documentos/Sprints/Sprint_14_Planejamento.md
  docs/documentos/imagens/Sprint14/pareamento_s14.png.png
Labels: [Documentation], [EPS], [Organization], [Sprint]

#260 Is248 melhorar qualidade de codigo
  .codeclimate.yml
  src/App.js
  src/components/Form.jsx
  src/components/FormDoctorForm.jsx
  src/components/FormUpdate.jsx
  src/components/Modal.jsx
  src/components/ModalForm.jsx
  src/components/NavBar.jsx
  src/components/PrivateRouter.js
  src/components/localizer.jsx
  src/pages/DoctorForm.jsx
  src/pages/DoctorStatus.jsx
  src/pages/HomePage.jsx
  src/pages/LoginPage.jsx
  src/pages/RegistrationAdmin.jsx
  src/pages/ScheduleTable.jsx
  src/pages/UpdateSchedule.jsx
Labels: [Frontend], [MDS], [React], [Technical Stories]

#268 Starting sprint 14 results
  docs/documentos/Sprints/Sprint_14_Resultado.md
  docs/documentos/imagens/Sprint14/burndown14.png
  docs/documentos/imagens/Sprint14/retrospectiva14.png
  docs/documentos/imagens/Sprint14/velocity14.png
Labels: [Documentation], [EPS], [Organization], [Sprint]

#272 refatorar geração de pdf.
  src/App.js
  src/components/NavBar.jsx
  src/components/SideBar.jsx
  src/css/ScheduleTable.css
  src/css/SideBar.css
  src/css/bootstrap.css
  src/pages/DoctorForm.jsx
  src/pages/HomePage.jsx
  src/pages/ScheduleTable.jsx
Labels: [Backend], [Bug], [Django], [MDS], [MICROSERVICE], [Urgent]

#269 Is249 teste de backend
  tests/test_views.py
Labels: [Backend], [Django], [MDS], [Technical Stories]

#279 Is114 teste de backend
  .coveragerc
  schedule/admin.py
  schedule/migrations/0003_auto_20180621_2201.py
  schedule/migrations/0004_auto_20180621_2227.py
  schedule/models/__init__.py
  schedule/models/calendars.py
  schedule/models/events.py
  schedule/models/rules.py
  schedule/periods.py
  schedule/serializer.py
  schedule/urls.py
  schedule/views.py
  src/components/Form.jsx
  src/components/FormDoctorForm.jsx
  src/components/FormUpdate.jsx
  tests/test_calendar.py
  tests/test_event.py
  tests/test_occurrence.py
  tests/test_periods.py
  tests/test_rule.py
  tests/test_user.py
  tests/test_views.py
  user/tests.py
  user/views.py
Labels: [Backend], [Django], [MDS], [Technical Stories], [Urgent]

#299 Changing laguage definitions
  src/pages/ScheduleTable.jsx
Labels: [Frontend], [React], [Technical Stories]

#300 Frontend adjustments
  src/components/Footer.js
  src/css/404Page.css
  src/css/DoctorForm.css
  src/css/HomePage.css
  src/css/NavBar.css
  src/css/bootstrap.css
  src/css/footer.css
  src/pages/HomePage.jsx
  src/pages/LoginPage.jsx
  src/pages/RegistrationAdmin.jsx
  src/pages/ScheduleTable.jsx
Labels: [Frontend], [React]
